name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug tag
        run: |
          echo "Tag: ${{ github.ref_name }}"

      - name: Build and push Docker image
        uses: Staffbase/gitops-github-action@v6.4
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-registry: ghcr.io
          docker-image: ghcr.io/${{ github.repository }}
          docker-custom-tag: ${{ github.ref_name }}
          docker-file: Dockerfile
          docker-build-target: ""
          docker-build-provenance: true
          docker-disable-retagging: true
          working-directory: .