name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ghcr.io/${{ github.repository }}
          tag: ${{ github.ref_name }}
          publish: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          dockerUser: ${{ github.actor }}
          dockerPassword: ${{ secrets.GITHUB_TOKEN }}
          dockerServer: ghcr.io
          context: .
          dockerFile: Dockerfile