name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and publish Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ github.repository }} # e.g., smarts-uz/js-docker-r
          image-tag: ${{ github.ref_name }} # Use ref_name to get clean branch (main) or tag (v1.0.0)
          # Remove extract-git-tag to avoid invalid tag format