name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        id: build
        uses: cloudposse/github-action-docker-build-push@v1.17.2
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          tags: ${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}
