name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.29.2  # Specify a recent stable v2 version to avoid v1
          cache-binary: true

      - name: Run Docker Compose
        run: docker compose -f docker-compose.yaml up -d

      - name: Build and push Docker image
        id: build
        uses: docker/bake-action@v6
        with:
          source: .
          push: true
          set: |
            *.tags=registry.hub.docker.com/ramz001/js-docker-test:latest
            *.platform=linux/amd64,linux/arm64
        env:
          DOCKER_BUILD_SUMMARY: true
          DOCKER_BUILD_RECORD_UPLOAD: true

    outputs:
      image: registry.hub.docker.com/ramz001/js-docker-test
      tag: latest